import { useState, useEffect } from 'react'
import axios from 'axios'
import Head from 'next/head'

import Page from '../components/Page'


export default function Home() {
  const [users, setUsers] = useState([])
  const [loading, setLoading] = useState([])

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true)
      const res = await axios.get('/users?_sort=createdAt&_order=desc')
      setUsers(res.data)
      setLoading(false)
    }

    fetchData()
  },[])

  if(loading) return <h2>Loading....</h2>
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Page users={users} />
      </main>
    </div>
  )
}
